apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-accounts-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-accounts-api
  template:
    metadata:
      labels:
        app: user-accounts-api
        namespace: default
    spec:
      serviceAccountName: api-service-account
      containers:
        - image: $IMAGE
          name: user-accounts-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: bakery-db-secrets
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: bakery-db-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bakery-db-secrets
                  key: DB_USER
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: bakery-db-secrets
                  key: DB_PWD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key-secret
                  key: JWT_SECRET_KEY
      imagePullSecrets: # Be sure the token name matches what you created on K8s
        - name: user-accounts-feature-deploy-token
