apiVersion: v1
kind: Service
metadata:
  name: user-accounts-api-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: user-accounts-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
